### ISSUE TITLE
negative offset in skip(TranscodingStream)

### ISSUE THREAD

**Issue by denius** [bicycle1885/TranscodingStreams.jl#76]
Hello!
I'm trying to parse a buffered file, but
```
skipchars(isspace, TranscodingStream(Noop(), IOBuffer(" test")))
```
yields ```ERROR: ArgumentError: negative offset``` due to https://github.com/bicycle1885/TranscodingStreams.jl/blob/af4327071debdc989b3777772b69bfd34af6fbd8/src/stream.jl#L224
in spite of in ```julia/base``` negative offsets are allowed: https://github.com/JuliaLang/julia/blob/95fcde9dda4261ebd9dd2eb694b46fc74e472ef6/base/iobuffer.jl#L235

**Comment by bicycle1885** [comment]
`IOBuffer` can support this feature because it keeps all data in its buffer. However, it is generally impossible to support this in `TranscodingStream` because it may discard data that are already read or skipped. Negative offsets may work but it depends on the internal state of the buffered data. I do not want to support that kind of unreliable functions because you cannot predict the result before calling it.
